# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-08 00:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='{"saturday": {"morning": {"now": "", "working": "", "notworking": ""}, "evening": {"now": "", "working": "", "notworking": ""}, "afternoon": {"now": "", "working": "", "notworking": ""}}, "sunday": {"morning": {"now": "", "working": "", "notworking": ""}, "evening": {"now": "", "working": "", "notworking": ""}, "afternoon": {"now": "", "working": "", "notworking": ""}}, "thursday": {"morning": {"now": "", "working": "", "notworking": ""}, "evening": {"now": "", "working": "", "notworking": ""}, "afternoon": {"now": "", "working": "", "notworking": ""}}, "friday": {"morning": {"now": "", "working": "", "notworking": ""}, "evening": {"now": "", "working": "", "notworking": ""}, "afternoon": {"now": "", "working": "", "notworking": ""}}, "tuesday": {"morning": {"now": "", "working": "", "notworking": ""}, "evening": {"now": "", "working": "", "notworking": ""}, "afternoon": {"now": "", "working": "", "notworking": ""}}, "wednesday": {"morning": {"now": "", "working": "", "notworking": ""}, "evening": {"now": "", "working": "", "notworking": ""}, "afternoon": {"now": "", "working": "", "notworking": ""}}, "monday": {"morning": {"now": "", "working": "", "notworking": ""}, "evening": {"now": "", "working": "", "notworking": ""}, "afternoon": {"now": "", "working": "", "notworking": ""}}}', verbose_name='My Activity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bulk_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='If you had one ultimate wish, what would it be？')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(max_length=128, null=True, verbose_name='How i want to be involved:')),
                ('text2', models.TextField(max_length=128, null=True, verbose_name='Who i want to help me in my NDIS planning meeting')),
                ('text3', models.TextField(max_length=128, null=True, verbose_name='What my NDIS representative needs to know about how i communication:')),
                ('text4', models.TextField(max_length=128, null=True, verbose_name='Who makes the final decisions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(max_length=128, null=True)),
                ('text2', models.TextField(max_length=128, null=True)),
                ('text3', models.TextField(max_length=128, null=True)),
                ('text4', models.TextField(max_length=128, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name='My programs and therapy supports: ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='[]', verbose_name='My health and wellbeing')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Importance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_family', models.TextField(max_length=128, null=True, verbose_name='How i want to be involved:')),
                ('work_school', models.TextField(max_length=128, null=True, verbose_name='How i want to be involved:')),
                ('very_close_top', models.TextField(max_length=128, null=True, verbose_name='Who i want to help me in my NDIS planning meeting')),
                ('very_close_bottom', models.TextField(max_length=128, null=True, verbose_name='What my NDIS representative needs to know about how i communication:')),
                ('very_close_left', models.TextField(max_length=128, null=True, verbose_name='Who makes the final decisions')),
                ('very_close_right', models.TextField(max_length=128, null=True, verbose_name='Who makes the final decisions')),
                ('friends', models.TextField(max_length=128, null=True, verbose_name='Who makes the final decisions')),
                ('home_supporters', models.TextField(max_length=128, null=True, verbose_name='Who makes the final decisions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Long_term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='What would you like to achieve in the next five years? ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(max_length=20, verbose_name='What type of home i live in?')),
                ('text2', models.TextField(max_length=20, verbose_name='The people i usually live with:')),
                ('text3', models.TextField(max_length=20, verbose_name='Who helps me at home?')),
                ('text4', models.TextField(max_length=128, verbose_name='What do they help me with？')),
                ('text5', models.TextField(max_length=64, verbose_name='Do i use any equipment or other things to help me at home?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name='My programs and therapy supports: ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Short_term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='What would you like to achieve in the next 12months? ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('communication', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MMW.Communication')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='[]', verbose_name='If you had one ultimate wish, what would it be？')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhoIAm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(max_length=128, null=True, verbose_name='what is important to me?')),
                ('text2', models.TextField(max_length=128, null=True, verbose_name='What do i like about myself?')),
                ('text3', models.TextField(max_length=64, null=True, verbose_name='What do other people like about me?')),
                ('text4', models.TextField(max_length=128, null=True, verbose_name='How to best support me:')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhoIAmHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(max_length=128, null=True)),
                ('text2', models.TextField(max_length=128, null=True)),
                ('text3', models.TextField(max_length=128, null=True)),
                ('text4', models.TextField(max_length=128, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name='My wish:')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='whoiam',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MMW.WhoIAm'),
        ),
    ]
