# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-26 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMW', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='date',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='user@qq.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='text1',
            field=models.TextField(default='awere'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='text2',
            field=models.TextField(default='qwe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='text3',
            field=models.TextField(default='eee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='text4',
            field=models.TextField(default='sdddf'),
            preserve_default=False,
        ),
    ]
