# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-02 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MMW', '0003_auto_20170402_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='whoiam',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MMW.WhoIAm'),
        ),
    ]
