# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-02 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MMW', '0004_userinfo_whoiam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(max_length=128, null=True, verbose_name='How i want to be involved:')),
                ('text2', models.TextField(max_length=128, null=True, verbose_name='Who i want to help me in my NDIS planning meeting')),
                ('text3', models.TextField(max_length=128, null=True, verbose_name='What my NDIS representative needs to know about how i communication:')),
                ('text4', models.TextField(max_length=128, null=True, verbose_name='Who makes the final decisions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='communication',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MMW.Communication'),
        ),
    ]
